### ISSUE TITLE
community.okd breaks Ansible 5 and 6 tests

### ISSUE THREAD

**Issue by felixfontein** [openshift/community.okd#148]
Currently community.okd requires kubernetes.core 2.1.x or 2.2.x, but Ansible 5 and 6 include kubernetes.core 2.3.0 since Ansible 5.6.0 (released on April 5th). This basically breaks community.okd in Ansible 5.6.0, and this should be fixed ASAP. Right now ansible-core does not check whether the correct versions are installed, but ansible-galaxy does, so installing the collections from Ansible 5.6.0 manually with `ansible-galaxy collection install` is not possible (when using https://github.com/ansible-community/ansible-build-data/blob/main/5/galaxy-requirements.yaml), which in particular makes it impossible to build an Execution Environment for Ansible 5.6.0 (https://github.com/ansible-community/images/pull/22). Please fix this ASAP. The next Ansible 5 release is supposed to happen on April 26th, it would be great if this could be fixed by then.

**Comment by gravesm** [comment]
Unfortunately, this is unlikely to be fixed by tomorrow. Our CI is currently blocking a new release and we do not have the capacity to address this in such a short time frame.

**Comment by jillr** [comment]
@felixfontein Please include whatever versions of the kubernetes and okd collections will not break the package build (presumably whatever we shipped in 5.5.0).  Let me know if you want/need reviews of ansible.in changes.

**Comment by felixfontein** [comment]
@jillr hmm, that would require downgrading kubernetes.core from 2.3.0 to 2.2.1. Doing that for Ansible 5.7.0 would be a breaking change IMO. But we can do that for Ansible 6. That will lead to the awkward situation though that Ansible the latest 5.x.0 contains a newer version of kubernetes.core than Ansible 6.0.0 does (assuming community.okd isn't fixed before the Ansible 6.0.0 feature freeze on May 24th).

CC @dmsimard

**Comment by felixfontein** [comment]
If this isn't fixed, I guess we'd have to downgrade kubernetes.core in Ansible 6 to 2.2.1 then and keep it there until community.okd is fixed.

**Comment by felixfontein** [comment]
[community.okd 2.2.0 has been released yesterday](https://github.com/openshift/community.okd/releases/tag/2.2.0) which should fix this problem. At least until kubernetes.core updates to 2.4.0.
