### ISSUE TITLE
Version conflict with kubernetes.core in Ansible package

### ISSUE THREAD

**Issue by felixfontein** [openshift/community.okd#183]
Currently test builds of the Ansible package fail due to a version conflict:
```
ERROR: community.okd version_conflict: kubernetes.core-2.4.0 but needs >=2.1.0,<2.4.0
```
(From what I understand #181 should fix this.)

**Comment by abikouo** [comment]
@felixfontein yes it should fix this

**Comment by felixfontein** [comment]
Closing since this is resolved now. Thanks!
