### ISSUE TITLE
Configure Ingress Ip and Egress Ip in openshift cluster 4.10 Using ansible code

### ISSUE THREAD

**Issue by SOMISETTYSAITEJA2K20** [openshift/community.okd#217]
In Openshift SDN network we want configure ingress IP and egress IP using ansible code but I am unable to any module in k8s collections and Openshift collections.
Can anyone please help me in finding modules doing In ansible code....

**Comment by gravesm** [comment]
@SOMISETTYSAITEJA2K20 Could you clarify what problem it is that you are having? We would need to know what version of the collection and ansible you are using, and an example playbook that we can use to reproduce your issue. If you are just looking for help with how to use ansible or this collection, the best place to ask will be the [ansible community forum](https://forum.ansible.com/).
