### ISSUE TITLE
Support for automating the lifecycle of builds in OpenShift

### ISSUE THREAD

**Issue by tima** [openshift/community.okd#32]
#### SUMMARY

Module(s) for automating the lifecycle of builds in OpenShift

##### ISSUE TYPE
- Feature Idea

##### COMPONENT NAME

TBD

##### ADDITIONAL INFORMATION

This implementation would only support v2 of the build API which is currently under development.

**Comment by alinabuzachis** [comment]
Hello @tima, can we close this issue as it seems it depends on an OCP3 feature?

**Comment by tima** [comment]
BuildRequests is a OCP v3 feature, but this issue is reminder to implement OCP "build v2" once it is stable. We got a fair bit of feedback that users would find this useful, but the new API was under development and we were advised to wait on doing anything. So I'd prefer we leave this open to track doing this.
