### ISSUE TITLE
Implement action groups for OKD modules

### ISSUE THREAD

**Issue by tima** [openshift/community.okd#41]
##### SUMMARY

As a convenience for users, all OKD modules should enable them to use module_defaults to feed values to common parameters. This should be like and consistent with that found in the kubernetes collection:

https://github.com/ansible-collections/community.kubernetes/blob/main/meta/runtime.yml

##### ISSUE TYPE

- Feature Idea

##### COMPONENT NAME

meta/runtime.yml

**Comment by petracvv** [comment]
Hey with ansible 2.11 out now, do you plan on revisiting this?

**Comment by gravesm** [comment]
@petracvv My understanding is that this did not make it into 2.11 and is scheduled for 2.12. See: https://gist.github.com/s-hertel/725ecc719b5301e76c571aca58d39bd3 and https://github.com/ansible/ansible/pull/74039. We do intend to implement this once the functionality has been built into Ansible core.
